import { DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, NoSuchKey, NotFound, PutObjectCommand } from "@aws-sdk/client-s3";
import { getS3Client } from "./client";
import { getStorageConfig } from "./config";
import { StorageOperationError } from "./errors";
import { validateStorageKey } from "./keys";

export interface UploadBufferInput {
  key: string;
  body: Buffer;
  contentType: string;
}

/**
 * Server-side direct upload — for apps/worker, which already has the
 * generated bytes in memory (an AudioProvider's `generateAudio()` result)
 * and has no reason to round-trip through a presigned URL to upload its
 * own output. Browser uploads (ProjectFile CSV imports, etc.) should use
 * getUploadUrl() instead — never route a user's raw upload through this
 * function's own process.
 */
export async function uploadBuffer(input: UploadBufferInput): Promise<{ key: string }> {
  const key = validateStorageKey(input.key);
  const config = getStorageConfig();
  try {
    await getS3Client().send(
      new PutObjectCommand({
        Bucket: config.bucket,
        Key: key,
        Body: input.body,
        ContentType: input.contentType,
        ContentLength: input.body.length,
      }),
    );
    return { key };
  } catch (cause) {
    throw new StorageOperationError("uploadBuffer", key, cause);
  }
}

export async function deleteObject(key: string): Promise<void> {
  const validKey = validateStorageKey(key);
  const config = getStorageConfig();
  try {
    await getS3Client().send(new DeleteObjectCommand({ Bucket: config.bucket, Key: validKey }));
  } catch (cause) {
    throw new StorageOperationError("deleteObject", validKey, cause);
  }
}

/**
 * Pure stream-to-buffer step, split out from downloadObject() so it can be
 * unit tested with a fake `{ transformToByteArray }` stub — no S3/network
 * involved. `transformToByteArray()` is the SdkStreamMixin helper
 * @aws-sdk/client-s3 attaches to every GetObjectCommand response body in
 * Node (see @smithy/types' SdkStreamMixin) — not a hand-rolled stream
 * reader, so there's no chunking/encoding edge case to get wrong here.
 */
export async function bodyToBuffer(body: { transformToByteArray(): Promise<Uint8Array> }): Promise<Buffer> {
  const bytes = await body.transformToByteArray();
  return Buffer.from(bytes);
}

/**
 * Downloads a full object into memory — used by the audio merge/export job
 * handler (apps/worker) to pull each scene's generated audio out of the
 * bucket before handing the bytes to ffmpeg. Not meant for large files;
 * Audio Studio's per-scene clips are small enough that streaming to disk
 * isn't worth the complexity yet.
 */
export async function downloadObject(key: string): Promise<Buffer> {
  const validKey = validateStorageKey(key);
  const config = getStorageConfig();
  try {
    const result = await getS3Client().send(new GetObjectCommand({ Bucket: config.bucket, Key: validKey }));
    if (!result.Body) {
      throw new Error("response had no Body");
    }
    return await bodyToBuffer(result.Body);
  } catch (cause) {
    if (cause instanceof NoSuchKey) {
      throw new StorageOperationError("downloadObject", validKey, new Error("object does not exist"));
    }
    throw new StorageOperationError("downloadObject", validKey, cause);
  }
}

export interface ObjectMetadata {
  exists: boolean;
  sizeBytes?: number;
  contentType?: string;
}

/**
 * Cheap existence + metadata check without downloading the object — used
 * to confirm a browser-uploaded ProjectFile actually landed before
 * creating the DB row for it, and to backfill sizeBytes/mimeType.
 */
export async function headObject(key: string): Promise<ObjectMetadata> {
  const validKey = validateStorageKey(key);
  const config = getStorageConfig();
  try {
    const result = await getS3Client().send(new HeadObjectCommand({ Bucket: config.bucket, Key: validKey }));
    return {
      exists: true,
      sizeBytes: result.ContentLength,
      contentType: result.ContentType,
    };
  } catch (cause) {
    if (cause instanceof NotFound) {
      return { exists: false };
    }
    throw new StorageOperationError("headObject", validKey, cause);
  }
}
